version: '3'
services:
  boot-node-1:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: boot-node-1
    volumes: ["./data/boot-node-1:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --validator
      - --ws-external
      - --ws-port=9944
      - --rpc-external
      - --rpc-cors=all
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09858

  boot-node-2:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: boot-node-2
    volumes: ["./data/boot-node-2:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --validator
      - --ws-external
      - --ws-port=9944
      - --rpc-external
      - --rpc-cors=all
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09859
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
      - "8080:8000"

  boot-node-3:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: boot-node-3
    volumes: ["./data/boot-node-3:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --validator
      - --ws-external
      - --ws-port=9944
      - --rpc-external
      - --rpc-cors=all
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09860

  validator-node-1:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: validator-node-1
    volumes: ["./data/validator-node-1:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
      - --bob
      - --validator
      - --ws-external
      - --rpc-cors=all

  validator-node-2:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: validator-node-2
    volumes: ["./data/validator-node-2:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-2/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW
      - --alice
      - --validator
      - --ws-external
      - --rpc-cors=all

  validator-node-3:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: validator-node-3
    volumes: ["./data/validator-node-3:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      - --charlie
      - --validator
      - --ws-external
      - --rpc-cors=all

  validator-node-4:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: validator-node-4
    volumes: ["./data/validator-node-4:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW,/dns4/boot-node-2/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW,/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      - --dave
      - --validator
      - --ws-external
      - --rpc-cors=all

  validator-node-5:
    image: plugnet/plugblockchain:1.0.0-rc1
    container_name: validator-node-5
    volumes: ["./data/validator-node-5:/mnt/node"]
    command:
      - /usr/local/bin/substrate
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
      - --eve
      - --validator
      - --ws-external
      - --rpc-cors=all
      - -log=error

  # full-node-1:
  #   image: plugnet/plugblockchain:1.0.0-rc1
  #   container_name: full-node-1
  #   volumes: ["./data/full-node-1:/mnt/node"]
  #   command:
  #     - /usr/local/bin/substrate
  #     - --base-path=/mnt/node
  #     - --chain=dev
  #     - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
  #     - --ws-external
  #     - --rpc-cors=all
  #     - -lafg

  # full-node-2:
  #   image: plugnet/plugblockchain:1.0.0-rc1
  #   container_name: full-node-2
  #   volumes: ["./data/full-node-2:/mnt/node"]
  #   command:
  #     - /usr/local/bin/substrate
  #     - --base-path=/mnt/node
  #     - --chain=dev
  #     - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
  #     - --ws-external
  #     - --rpc-cors=all

  # full-node-1:
  #   image: plugnet/plugblockchain:1.0.0-rc1
  #   container_name: full-node-1
  #   volumes: ["./data/full-node-1:/mnt/node"]
  #   command:
  #     - /usr/local/bin/substrate
  #     - --base-path=/mnt/node
  #     - --chain=dev
  #     - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
  #     - --ws-external
  #     - --rpc-cors=all

  # full-node-3:
  #   image: plugnet/plugblockchain:1.0.0-rc1
  #   container_name: full-node-3
  #   volumes: ["./data/full-node-3:/mnt/node"]
  #   command:
  #     - /usr/local/bin/substrate
  #     - --base-path=/mnt/node
  #     - --chain=dev
  #     - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
  #     - --ws-external
  #     - --rpc-cors=all


